tbox::UmpireAllocator alias of umpire::Allocator
LLNL/SAMRAI pull request #148
Opened 2020-09-21 22:33 UTC by nselliott

tbox::UmpireAllocator is introduced as an alias for umpire::Allocator so that calling codes do not need to maintain separate code bases for calls to SAMRAI API when building with or without Umpire.  When SAMRAI is built without Umpire, tbox::UmpireAllocator is an empty struct that does nothing, but still a valid type.

2020-09-21 22:42 UTC, davidbeckingsale requested changes
Looks great. The only change I would suggest is just calling it tbox::Allocator rather than UmpireAllocator.

2020-09-21 22:47 UTC, nselliott commented
@davidbeckingsale I understand if you prefer I don't use the Umpire name in the datatype, but I'd like the name to convey more information than just "Allocator".  Perhaps "ResourceAllocator"?

2020-09-22 00:18 UTC, wliuphd submitted a review, later dismissed

2020-09-29 20:57 UTC, nselliott commented
LGTM

2020-09-29 22:08 UTC, merged